### ISSUE TITLE
Fails to get a server list.

### ISSUE THREAD

**Issue by Vad1mo** [synapticloopltd/scaleway-java-api#2]
I am trying to get a list of the servers

```
        def scalewayApiClient = new ScalewayApiClient(***", PARIS1);
        ServersResponse servers = scalewayApiClient.getAllServers(1, 100)
        for (server in servers.servers){
            println("${server.hostname}")
        }
```

this is the stacktrace 

```
synapticloop.scaleway.api.exception.ScalewayApiException: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
at [Source: {"servers": [{"state_detail": "booted", "image": {"default_bootscript": {"kernel": "http://169.254.42.24/kernel/x86_64-4.8.14-docker-2/vmlinuz-4.8.14-docker-2", "initrd": ............

line: 1, column: 7148] (through reference chain: synapticloop.scaleway.api.response.ServersResponse["servers"]->java.util.ArrayList[2]->synapticloop.scaleway.api.model.Server["extra_networks"]->java.lang.Object[][0])


	at synapticloop.scaleway.api.ScalewayApiClient.parseResponse(ScalewayApiClient.java:1054)
	at synapticloop.scaleway.api.ScalewayApiClient.getAllServers(ScalewayApiClient.java:238)
	at Deployer.deploy(Deployer.groovy:44)
	at DeployerTest.Deploy(DeployerTest.groovy:4)


	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:862)
	at com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer.deserialize(StringArrayDeserializer.java:106)
	at com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer.deserialize(StringArrayDeserializer.java:18)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
	at synapticloop.scaleway.api.ScalewayApiClient.parseJson(ScalewayApiClient.java:1071)
	at synapticloop.scaleway.api.ScalewayApiClient.parseResponse(ScalewayApiClient.java:1052)
	... 3 more
```

**Comment by synapticloop** [comment]
This is a tough one - the documentation is severely lacking - there is no example of a key "extra_networks" within the JSON examples - hence I don't know what to collect for the JSON parser.

If you add in the rest of the JSON returned from:

{"servers": [{"state_detail": "booted", "image": {"default_bootscript": {"kernel": "http://169.254.42.24/kernel/x86_64-4.8.14-docker-2/vmlinuz-4.8.14-docker-2", "initrd": ............
 (with the missing .....) 

I can add in the properties.

**Comment by Vad1mo** [comment]
All Serves have this entry.  I can't see anything in the Swagger API. It seems that the api is completly not in sync with the api spec.

![bildschirmfoto 2017-03-05 um 16 02 59](https://cloud.githubusercontent.com/assets/1492007/23588394/51e86266-01bd-11e7-975d-bfe7df8fe64c.png)

**Comment by synapticloop** [comment]
Yes, thanks for that - will push a new version soon...

**Comment by synapticloop** [comment]
Not getting through these details from my API calls:

             "extra_networks":  [
                
            ],

Version 0.9.2 has a fix

**Comment by Vad1mo** [comment]
now it works, thank you.
